module.exports = {
  'mso-ansi-font-size': ['large', 'larger', 'medium', 'small', 'smaller', 'x-large', 'x-small', 'xx-large', 'xx-small'],
  'mso-ansi-font-style': ['italic', 'normal', 'oblique'],
  'mso-ansi-font-weight': ['lighter', 'normal', 'bold', 'bolder'],
  'mso-ascii-font-family': ['auto', 'cursive', 'fantasy', 'monospace', 'sans-serif', 'serif'],
  'mso-bidi-flag': ['on', 'off'],
  'mso-bidi-font-style': ['italic', 'normal', 'oblique'],
  'mso-bidi-font-weight': ['lighter', 'normal', 'bold', 'bolder'],
  'mso-bidi-font-size': ['large', 'larger', 'medium', 'small', 'smaller', 'x-large', 'x-small', 'xx-large', 'xx-small'],
  'mso-bidi-font-family': ['auto', 'cursive', 'fantasy', 'monospace', 'sans-serif', 'serif'],
  'mso-highlight': ['auto', 'windowtext'],
  'mso-generic-font-family': ['auto', 'decorative', 'modern', 'roman', 'script', 'swiss'],
  'mso-element-frame-width': ['auto'],
  'mso-element': ['comment', 'comment-list', 'dropcap-dropped', 'dropcap-in-margin', 'endnote', 'endnote-continuation-notice', 'endnote-continuation-separator', 'endnote-list', 'endnote-separator', 'field-begin', 'field-end', 'field-separator', 'footer', 'footnote', 'footnote-continuation-notice', 'footnote-continuation-separator', 'footnote-list', 'footnote-separator', 'frame', 'header', 'none', 'paragraph-mark-properties', 'table-head'],
  'mso-element-left': ['center', 'inside', 'left', 'outside', 'right'],
  'mso-hide': ['all', 'none', 'screen'],
  'mso-color-alt': ['auto', 'windowtext'],
  'mso-line-height-rule': ['at-least', 'exactly'],
  'mso-line-height-alt': ['normal'],
}
